package com.mm.user.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@DynamoDBTable(tableName = "users") // Đánh dấu đây là một bảng DynamoDB
public class User {

    @DynamoDBHashKey // Đây là khóa chính (Partition Key)
    @DynamoDBAutoGeneratedKey // ID sẽ được tự động tạo
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "username-index") // Tạo chỉ mục để tìm kiếm nhanh theo username
    @DynamoDBAttribute
    private String username;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index") // Tạo chỉ mục để tìm kiếm nhanh theo email
    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String password;

    // Lưu trữ các quyền (roles) dưới dạng một tập hợp các chuỗi
    @DynamoDBAttribute
    private Set<String> roles;

    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }
}
